# SOPS Configuration
# This file contains PUBLIC keys only - safe to commit to version control
# Private keys are stored locally and NEVER committed

# =============================================================================
# HOW TO ADD A NEW HOST:
# 1. Generate host key during installation:
#    age-keygen -o /var/lib/sops-nix/key.txt
# 2. Get public key:
#    age-keygen -y /var/lib/sops-nix/key.txt
# 3. Add public key below
# 4. Re-encrypt all secrets:
#    sops updatekeys secrets/*.yaml
# =============================================================================

keys:
  # Admin key - your personal key for editing secrets
  # Location: ~/.config/sops/age/keys.txt (on your management machine)
  - &admin REPLACE_WITH_YOUR_PERSONAL_PUBLIC_KEY
  
  # Host keys - generated on each machine during installation
  # Location on host: /var/lib/sops-nix/key.txt
  - &sukkub REPLACE_WITH_SUKKUB_PUBLIC_KEY
  - &azazel REPLACE_WITH_AZAZEL_PUBLIC_KEY

creation_rules:
  # SSH secrets - shared between all hosts (keys and config)
  - path_regex: secrets/ssh\.yaml$
    key_groups:
      - age:
          - *admin
          - *sukkub
          - *azazel
  
  # Common secrets - all hosts can decrypt
  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
          - *admin
          - *sukkub
          - *azazel
  
  # Sukkub-specific secrets
  - path_regex: secrets/sukkub\.yaml$
    key_groups:
      - age:
          - *admin
          - *sukkub
  
  # Azazel-specific secrets
  - path_regex: secrets/azazel\.yaml$
    key_groups:
      - age:
          - *admin
          - *azazel
