# SOPS Configuration
# This file contains PUBLIC keys only - safe to commit to version control
# Private keys are stored locally and NEVER committed

# =============================================================================
# HOW TO ADD A NEW HOST:
# 1. Generate host key during installation:
#    age-keygen -o /var/lib/sops-nix/key.txt
# 2. Get public key:
#    age-keygen -y /var/lib/sops-nix/key.txt
# 3. Add public key below
# 4. Re-encrypt all secrets:
#    sops updatekeys secrets/*.yaml
# =============================================================================

keys:
  # Admin key - your personal key for editing secrets
  # Location: ~/.config/sops/age/keys.txt (on your management machine)
  - &admin age1t73dnh9pj2qsz3rfqgq54t2pyxh8ew6w8xsta7pfwmmxmsjswgrshue8gx 
  
  # Host keys - generated on each machine during installation
  # Location on host: /var/lib/sops-nix/key.txt
  - &sukkub age1vqp07rzptmjvcd0df7ppwmwjm77qckckjpht62rk246rypuy9pns8t9c32
  - &azazel age1t73dnh9pj2qsz3rfqgq54t2pyxh8ew6w8xsta7pfwmmxmsjswgrshue8gx

creation_rules:
  # SSH secrets - shared between all hosts (keys and config)
  - path_regex: secrets/ssh\.yaml$
    key_groups:
      - age:
          - *admin
          - *sukkub
          - *azazel
  
  # WiFi secrets - shared between all hosts (passwords for home, work, etc.)
  - path_regex: secrets/wifi\.env$
    key_groups:
      - age:
          - *admin
          - *sukkub
          - *azazel
  
  # Common secrets - all hosts can decrypt
  - path_regex: secrets/common\.yaml$
    key_groups:
      - age:
          - *admin
          - *sukkub
          - *azazel
  
  # Sukkub-specific secrets
  - path_regex: secrets/sukkub\.yaml$
    key_groups:
      - age:
          - *admin
          - *sukkub
  
  # Azazel-specific secrets
  - path_regex: secrets/azazel\.yaml$
    key_groups:
      - age:
          - *admin
          - *azazel
