# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/569b4de6-df68-4287-80c0-824dcb3c1e84";
    fsType = "btrfs";
    options = ["subvol=@" "compress=zstd" "noatime"];
  };

  boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-uuid/9ca46adc-6511-47e2-ad20-0f23372ddc1f";
    allowDiscards = true;
    bypassWorkqueues = true;
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/569b4de6-df68-4287-80c0-824dcb3c1e84";
    fsType = "btrfs";
    options = ["subvol=@home" "compress=zstd" "noatime"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/569b4de6-df68-4287-80c0-824dcb3c1e84";
    fsType = "btrfs";
    options = ["subvol=@nix"];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/disk/by-uuid/569b4de6-df68-4287-80c0-824dcb3c1e84";
    fsType = "btrfs";
    options = ["subvol=@snapshots"];
  };

  fileSystems."/var/cache" = {
    device = "/dev/disk/by-uuid/569b4de6-df68-4287-80c0-824dcb3c1e84";
    fsType = "btrfs";
    options = ["subvol=@cache"];
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/569b4de6-df68-4287-80c0-824dcb3c1e84";
    fsType = "btrfs";
    options = ["subvol=@tmp"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/569b4de6-df68-4287-80c0-824dcb3c1e84";
    fsType = "btrfs";
    options = ["subvol=@log"];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/569b4de6-df68-4287-80c0-824dcb3c1e84";
    fsType = "btrfs";
    options = ["subvol=@swap" "noatime"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6D0E-5C6B";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
