# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/16e16946-d184-4e05-9a04-cfe341d110ce";
    fsType = "btrfs";
    options = ["subvol=@"];
  };

  boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-uuid/5716b2d7-af86-42af-a314-6fa80a948844";
    allowDiscards = true;
    bypassWorkqueues = true;
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/16e16946-d184-4e05-9a04-cfe341d110ce";
    fsType = "btrfs";
    options = ["subvol=@home"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/16e16946-d184-4e05-9a04-cfe341d110ce";
    fsType = "btrfs";
    options = ["subvol=@nix"];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/disk/by-uuid/16e16946-d184-4e05-9a04-cfe341d110ce";
    fsType = "btrfs";
    options = ["subvol=@snapshots"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/16e16946-d184-4e05-9a04-cfe341d110ce";
    fsType = "btrfs";
    options = ["subvol=@log"];
  };

  fileSystems."/var/cache" = {
    device = "/dev/disk/by-uuid/16e16946-d184-4e05-9a04-cfe341d110ce";
    fsType = "btrfs";
    options = ["subvol=@cache"];
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/16e16946-d184-4e05-9a04-cfe341d110ce";
    fsType = "btrfs";
    options = ["subvol=@tmp"];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/16e16946-d184-4e05-9a04-cfe341d110ce";
    fsType = "btrfs";
    options = ["subvol=@swap" "noatime"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0BFD-BA25";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
