# lib/secrets.nix
#
# Generates .sops.yaml from the fleet instead of maintaining it by hand.
#
# Who may decrypt a secret file (its audience):
#   - every admin key from hosts/fleet.nix (`sops.admins`), always;
#   - every host whose NixOS configuration references the file, i.e. it
#     appears as `sopsFile` of a `sops.secrets.<n>` entry of the system or
#     of one of the host's Home Manager users;
#   - every host that lists the file in `sops.extraSecrets` of its machine
#     file (for secrets a host must be able to read before a module uses
#     them).
# Files that no host uses (host SSH keys in secrets/hosts/, new secrets
# before a module references them) are encrypted for the admin keys only.
#
# Host keys come from `sops.ageKey` in hosts/machines/<host>.nix. A key
# used under several names (azazel's key is the admin key) is written once.
#
# Returns:
#   text           - contents of the generated .sops.yaml
#   secretFiles    - every encrypted file in secrets/ (repo-relative)
#   configProblems - [] when the committed .sops.yaml equals `text`
#   recipientProblems - [] when every encrypted file is encrypted for
#                    exactly the keys its rule names
{
  lib,
  inventory,
  nixosConfigurations,
}: let
  # Flake source root. Paths of sops files referenced by modules live
  # below it, e.g. /nix/store/<hash>-source/secrets/wifi.env.
  root = toString ../.;

  relPath = file: let
    s = toString file;
  in
    if lib.hasPrefix "${root}/" s
    then lib.removePrefix "${root}/" s
    else throw "sops file ${s} is outside the repository; secret files must live in secrets/";

  admins = inventory.sops.admins;
  machines = inventory.machines;
  hostNames = builtins.attrNames machines;

  # --- audiences --------------------------------------------------------

  sopsFilesOf = secrets: map (s: s.sopsFile) (lib.attrValues secrets);

  filesUsedBy = name: let
    config = nixosConfigurations.${name}.config;
    homeUsers = lib.attrValues (config.home-manager.users or {});
  in
    map relPath (
      sopsFilesOf config.sops.secrets
      ++ lib.concatMap (u: sopsFilesOf (u.sops.secrets or {})) homeUsers
    )
    ++ (machines.${name}.sops.extraSecrets or []);

  # file -> [host]
  audiences =
    lib.foldl' (acc: name:
      lib.foldl' (acc': file: acc' // {${file} = lib.unique ((acc'.${file} or []) ++ [name]);}) acc
      (filesUsedBy name)) {}
    hostNames;

  # --- keys ---------------------------------------------------------------

  # Every named key, admins first, then hosts in alphabetical order.
  namedKeys =
    lib.mapAttrsToList (name: key: {inherit name key;}) admins
    ++ map (name: {
      inherit name;
      key = machines.${name}.sops.ageKey;
    })
    hostNames;

  # key -> [names], in the order above.
  namesOfKey =
    lib.foldl' (acc: k: acc // {${k.key} = (acc.${k.key} or []) ++ [k.name];}) {} namedKeys;

  # Keys in order of first appearance; the first name is the YAML anchor.
  uniqueKeys = lib.unique (map (k: k.key) namedKeys);
  anchorOf = key: builtins.head namesOfKey.${key};

  adminKeys = lib.unique (lib.attrValues admins);

  # Keys that must be able to decrypt a file.
  keysFor = file:
    lib.unique (adminKeys ++ map (h: machines.${h}.sops.ageKey) (audiences.${file} or []));

  # --- .sops.yaml ---------------------------------------------------------

  ruleFiles = lib.sort (a: b: a < b) (builtins.attrNames audiences);

  keyLine = key: let
    names = namesOfKey.${key};
    others = builtins.tail names;
  in
    "  - &${anchorOf key} ${key}"
    + lib.optionalString (others != []) " # also: ${lib.concatStringsSep ", " others}";

  rule = regex: keys:
    "  - path_regex: '${regex}'\n"
    + "    key_groups:\n"
    + "      - age:\n"
    + lib.concatMapStrings (k: "          - *${anchorOf k}\n") keys;

  text =
    ''
      # .sops.yaml - GENERATED, do not edit by hand.
      #
      # Regenerate and re-encrypt with `nix run .#sops-config` after changing
      # hosts/fleet.nix, a machine file or which secrets a module uses.
      # Generated by lib/secrets.nix; `nix flake check` fails when this file
      # or the recipients of an encrypted file are out of date.
      # See secrets/README.md.

      keys:
    ''
    + lib.concatMapStrings (k: keyLine k + "\n") uniqueKeys
    + ''

      creation_rules:
    ''
    + lib.concatMapStrings (file: rule "(^|/)${lib.escapeRegex file}$" (keysFor file)) ruleFiles
    + "  # Everything else in secrets/ (host SSH keys, secrets no host uses\n"
    + "  # yet): admin keys only.\n"
    + rule "(^|/)secrets/" adminKeys;

  # --- checks -----------------------------------------------------------

  # Encrypted files in secrets/, recursively.
  notSecret = file: builtins.elem (baseNameOf file) ["README.md" ".gitignore"] || lib.hasSuffix ".example" file;
  listFiles = dir: prefix:
    lib.concatLists (lib.mapAttrsToList (n: type:
      if type == "directory"
      then listFiles (dir + "/${n}") "${prefix}${n}/"
      else ["${prefix}${n}"])
    (builtins.readDir dir));
  secretFiles = builtins.filter (f: !(notSecret f)) (listFiles ../secrets "secrets/");

  # Age recipients stored in the sops metadata of a file (YAML, JSON,
  # dotenv and binary files all keep them in plain text).
  ageKeysIn = file:
    lib.unique (lib.concatLists (builtins.filter builtins.isList
        (builtins.split "(age1[02-9ac-hj-np-z]{58})" (builtins.readFile (../. + "/${file}")))));

  describe = key: lib.concatStringsSep "/" (namesOfKey.${key} or ["unknown key ${key}"]);

  recipientProblems = lib.concatMap (file: let
    expected = keysFor file;
    actual = ageKeysIn file;
    missing = builtins.filter (k: !(builtins.elem k actual)) expected;
    extra = builtins.filter (k: !(builtins.elem k expected)) actual;
  in
    lib.optional (missing != []) "${file}: not encrypted for ${lib.concatMapStringsSep ", " describe missing}"
    ++ lib.optional (extra != []) "${file}: still encrypted for ${lib.concatMapStringsSep ", " describe extra}")
  secretFiles;

  committed =
    if builtins.pathExists ../.sops.yaml
    then builtins.readFile ../.sops.yaml
    else null;
  configProblems =
    lib.optional (committed != text)
    ".sops.yaml differs from the configuration (secret used by a new host, new key, new file?)";
in {
  inherit text secretFiles audiences configProblems recipientProblems;
}
