# modules/servers/ai/searxng.nix
#
# SearXNG — privacy-respecting metasearch engine.
# Used by Open-WebUI's web search feature to give the LLM internet access.
#
# Design decisions:
#   - OCI container (Podman) via virtualisation.oci-containers.
#   - Custom settings.yml injected via a bind-mounted config directory.
#   - settings.yml is generated by a NixOS activation script so it's
#     always in sync with the Nix config, even after container updates.
#   - Listens on 127.0.0.1:8080 only — not exposed to LAN.
#   - Open-WebUI connects to http://127.0.0.1:8080 (host network mode).
#
# Ports:
#   8080 — HTTP (internal only, reached by Open-WebUI on same host)
#
# Volumes:
#   /mnt/data/searxng  →  /etc/searxng  (settings.yml + secret_key)
{
  pkgs,
  ...
}: {
  # ---------------------------------------------------------------------------
  # Generate SearXNG config directory and settings.yml.
  # Using an activation script so the config is always up-to-date and
  # the secret_key file is created on first run if missing.
  # ---------------------------------------------------------------------------
  system.activationScripts.searxng-config = {
    text = ''
      install -d -m 0750 /mnt/data/searxng

      # Generate a persistent secret key on first deploy only.
      KEY_FILE=/mnt/data/searxng/secret_key
      if [ ! -f "$KEY_FILE" ]; then
        ${pkgs.openssl}/bin/openssl rand -hex 32 > "$KEY_FILE"
        chmod 0600 "$KEY_FILE"
      fi
      SECRET_KEY=$(cat "$KEY_FILE")

      cat > /mnt/data/searxng/settings.yml << EOF
# SearXNG settings — managed by NixOS activation script.
# Do not edit manually; changes will be overwritten on next deploy.
use_default_settings: true

server:
  secret_key: "$SECRET_KEY"
  limiter: false       # disable rate limiting (internal use only)
  image_proxy: true
  base_url: "http://localhost:8080/"
  bind_address: "127.0.0.1:8080"

ui:
  default_locale: "en"
  default_theme: simple
  center_alignment: true

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"

engines:
  - name: google
    engine: google
    shortcut: g
  - name: duckduckgo
    engine: duckduckgo
    shortcut: d
  - name: wikipedia
    engine: wikipedia
    shortcut: w
    base_url: "https://en.wikipedia.org/"
  - name: github
    engine: github
    shortcut: gh
EOF
    '';
    # Run after tmpfiles so /mnt/data exists.
    deps = [ "specialfs" ];
  };

  virtualisation.oci-containers.containers.searxng = {
    image = "docker.io/searxng/searxng:latest";

    # Host network — same reasoning as Open-WebUI.
    extraOptions = [ "--network=host" ];

    environment = {
      SEARXNG_BIND_ADDRESS = "127.0.0.1:8080";
      # settings.yml is bind-mounted, so this just confirms the path.
      SEARXNG_SETTINGS_PATH = "/etc/searxng";
    };

    volumes = [
      "/mnt/data/searxng:/etc/searxng:rw"
    ];

    autoStart = true;
  };

  systemd.services."podman-searxng" = {
    after    = [ "mnt-data.mount" ];
    requires = [ "mnt-data.mount" ];
  };
}
