# fleet - one entry point for repository and fleet tasks (refactor stage 8,
# started in stage 5b; BACKLOG.md).
#
#   nix run .#fleet                  choose a task from a searchable list
#   nix run .#fleet -- <task> [...]  run a task directly, e.g.
#                                    nix run .#fleet -- monitoring apply --check
#   nix run .#fleet -- --help        list the tasks
#
# Run it from the repository on the admin workstation (azazel). A task that
# changes files validates them, stages them with `git add` and prints a
# ready-to-copy `git commit` command; it never commits.
#
# Adding a task: a function task_<words> and a line in TASKS below.

die() {
  gum style --foreground 1 "fleet: $*" >&2
  exit 1
}

info() {
  gum style --foreground 4 "$*"
}

warn() {
  gum style --foreground 3 "$*"
}

# Escape a value for a Nix double-quoted string.
nix_string() {
  local s=$1
  s=${s//\\/\\\\}
  s=${s//\"/\\\"}
  s=${s//\$\{/\\\$\{}
  printf '"%s"' "$s"
}

# "<task>|<description>"; the task is two words, the function name joins
# them with "_".
TASKS=(
  "device add|Add a device without NixOS (hosts/devices/), optionally install its monitoring agents"
  "monitoring apply|Install or update monitoring agents (node, smartctl, cadvisor) on devices without NixOS (Ansible)"
  "host new|Register a new NixOS machine (nix run .#new-host)"
  "host install|Install a registered machine with nixos-anywhere (nix run .#install-host)"
  "secrets update|Regenerate .sops.yaml and re-encrypt every secret for its audience (nix run .#sops-config)"
)

usage() {
  printf 'Usage: nix run .#fleet [-- <task> [options]]\n\nTasks:\n'
  local t
  for t in "${TASKS[@]}"; do
    printf '  %-18s %s\n' "${t%%|*}" "${t#*|}"
  done
  printf '\nmonitoring apply options: --agent <name> --check | --apply --all | --limit <device> (repeatable)\n'
}

# Prints the chosen task ("<word> <word>"), nothing when cancelled.
pick_task() {
  local lines=() t choice
  for t in "${TASKS[@]}"; do
    lines+=("$(printf '%-18s %s' "${t%%|*}" "${t#*|}")")
  done
  choice=$(printf '%s\n' "${lines[@]}" | gum filter --header "Choose a task (type to search, Esc to quit)" --height 15) || return 0
  local first second
  read -r first second _ <<<"$choice"
  printf '%s %s\n' "$first" "$second"
}

# The inventory as JSON (global `inventory`); `reload` after files changed.
inventory=""
load_inventory() {
  if [[ -n $inventory && ${1:-} != reload ]]; then
    return 0
  fi
  info "Reading the inventory..."
  inventory=$(nix eval --json .#inventory) || die "the inventory does not evaluate; fix it first"
}

# --- monitoring agents ----------------------------------------------------

# Monitoring agents installed with Ansible on devices without NixOS:
# "<agent>|<device field monitoring.X>|<playbook>|<metrics port>|<description>"
# The ports must match lib/monitoring.nix and the playbooks.
AGENTS=(
  "node|node|ansible/playbooks/node.yml|9100|node_exporter: CPU, memory, disks, network, systemd units"
  "smartctl|smartctl|ansible/playbooks/smartctl.yml|9633|smartctl_exporter: SMART of the disks (baremetal devices only)"
  "cadvisor|cadvisor|ansible/playbooks/cadvisor.yml|8080|cAdvisor: Docker containers"
)

agent_names() {
  local a
  for a in "${AGENTS[@]}"; do
    printf '%s\n' "${a%%|*}"
  done
}

# Sets agent_field, agent_playbook, agent_port for the agent $1.
agent_lookup() {
  local a name
  for a in "${AGENTS[@]}"; do
    IFS='|' read -r name agent_field agent_playbook agent_port _ <<<"$a"
    [[ $name == "$1" ]] && return 0
  done
  die "unknown agent $1 (known: $(agent_names | paste -sd' '))"
}

# Devices with monitoring.<field> = true, one per line.
agent_devices() {
  jq -r --arg f "$1" \
    '.devices | to_entries[] | select(.value.monitoring[$f] == true) | .key' <<<"$inventory"
}

ensure_collections() {
  local dir=ansible/.collections sum stamp
  sum=$(sha256sum ansible/requirements.yml | cut -d' ' -f1)
  stamp="$dir/.requirements.sha256"
  if [[ -f $stamp && $(<"$stamp") == "$sum" ]]; then
    return 0
  fi
  info "Installing Ansible collections (ansible/requirements.yml)..."
  rm -rf "$dir"
  mkdir -p "$dir"
  ansible-galaxy collection install -r ansible/requirements.yml -p "$dir" ||
    die "installing the Ansible collections failed"
  printf '%s\n' "$sum" >"$stamp"
}

# Ansible logs in through the SSH alias of each device, which comes from
# ~/.ssh/config.d/devices, generated by Home Manager from hosts/devices/.
# A device added since the last rebuild of this workstation has no alias
# yet; prints the devices whose alias does not point where the inventory
# says.
missing_ssh_aliases() {
  local d expected actual
  for d in "$@"; do
    expected=$(jq -r --arg d "$d" '.devices[$d] | (.ssh[$d].hostName // .lan.ip)' <<<"$inventory")
    actual=$(ssh -G "$d" 2>/dev/null | awk '$1 == "hostname" { print $2 }')
    [[ $actual == "$expected" ]] || printf '%s\n' "$d"
  done
}

# apply_agent <agent> <check|apply> <device>... ; returns 1 when an agent
# does not answer afterwards.
apply_agent() {
  local agent=$1 mode=$2
  shift 2
  local selected=("$@")
  agent_lookup "$agent"

  local missing
  missing=$(missing_ssh_aliases "${selected[@]}")
  if [[ -n $missing ]]; then
    warn "No SSH alias yet for: $(paste -sd' ' <<<"$missing")."
    warn "Rebuild this workstation first (nrs) so ~/.ssh/config.d/devices has them, then run: nix run .#fleet -- monitoring apply --agent $agent --limit <device>"
    return 1
  fi

  # Before installing, so ansible-galaxy knows the target directory is a
  # configured collections path.
  export ANSIBLE_CONFIG="$PWD/ansible/ansible.cfg"
  export ANSIBLE_COLLECTIONS_PATH="$PWD/ansible/.collections"
  ensure_collections

  # Inventory for Ansible: the group named like the agent, one host per
  # device, named like its SSH alias so the generated ssh config supplies
  # address, user and key. Playbooks set `become: true` at play level (the
  # roles keep `become: false` for their downloads on this machine); root
  # logins become root with su, because Debian guests may have no sudo,
  # other users with sudo. ansible_become itself is not set here: as a
  # variable it would override the roles' `become: false`.
  # Global, not local: the EXIT trap runs after this function returns.
  fleet_tmp=${fleet_tmp:-$(mktemp -d)}
  trap 'rm -rf "${fleet_tmp:-}"' EXIT
  jq --arg group "$agent" --args '
    .devices as $devs
    | {all: {children: {($group): {hosts: (
        $ARGS.positional
        | map({key: ., value: (
            if ($devs[.].ssh[.].user // "") == "root"
            then {ansible_become_method: "su"}
            else {}
            end)})
        | from_entries)}}}}' "${selected[@]}" <<<"$inventory" >"$fleet_tmp/inventory-$agent.json"

  local args=(-i "$fleet_tmp/inventory-$agent.json" "$agent_playbook" --diff)
  [[ $mode == check ]] && args+=(--check)

  info "ansible-playbook $agent_playbook ($mode) on: ${selected[*]}"
  ansible-playbook "${args[@]}" || die "ansible-playbook failed"

  [[ $mode == apply ]] || return 0

  # Is the agent answering?
  local d ip failed=0
  for d in "${selected[@]}"; do
    ip=$(jq -r --arg d "$d" '.devices[$d].lan.ip' <<<"$inventory")
    if curl -fsS -o /dev/null --max-time 10 "http://$ip:$agent_port/metrics"; then
      info "$d: $agent answers on http://$ip:$agent_port/metrics"
    else
      gum style --foreground 1 "$d: $agent does not answer on http://$ip:$agent_port/metrics"
      failed=1
    fi
  done
  return "$failed"
}

choose_mode() {
  local choice
  choice=$(gum choose --header "Mode" \
    "check  - dry run: show what would change, change nothing" \
    "apply  - install or update") || exit 0
  printf '%s\n' "${choice%% *}"
}

monitoring_server_hint() {
  local server
  server=$(jq -r '.monitoring.server' <<<"$inventory")
  info "Prometheus scrapes new targets once $server runs the current configuration (colmena apply --on $server)."
}

task_monitoring_apply() {
  local agent="" mode="" select_all=false limit=()
  while (($# > 0)); do
    case $1 in
      --agent)
        agent=${2:-}
        shift
        ;;
      --check) mode=check ;;
      --apply) mode=apply ;;
      --all) select_all=true ;;
      --limit)
        limit+=("${2:-}")
        shift
        ;;
      *) die "monitoring apply: unknown option $1 (see --help)" ;;
    esac
    shift
  done

  # Which agent.
  if [[ -z $agent ]]; then
    local lines=() a name desc
    for a in "${AGENTS[@]}"; do
      name=${a%%|*}
      desc=${a##*|}
      lines+=("$(printf '%-9s %s' "$name" "$desc")")
    done
    agent=$(gum choose --header "Agent" "${lines[@]}") || exit 0
    agent=${agent%% *}
  fi
  agent_lookup "$agent"

  # Devices that want it.
  load_inventory
  local devices=()
  mapfile -t devices < <(agent_devices "$agent_field")
  ((${#devices[@]} > 0)) ||
    die "no device sets monitoring.$agent_field = true; add it to hosts/devices/<name>.nix first"

  # Which of them.
  local selected=() d
  if ((${#limit[@]} > 0)); then
    for d in "${limit[@]}"; do
      printf '%s\n' "${devices[@]}" | grep -qx -- "$d" ||
        die "$d does not set monitoring.$agent_field = true"
    done
    selected=("${limit[@]}")
  elif $select_all; then
    selected=("${devices[@]}")
  else
    mapfile -t selected < <(gum choose --no-limit \
      --header "Devices for $agent (space toggles, enter confirms)" \
      --selected "$(
        IFS=,
        printf '%s' "${devices[*]}"
      )" "${devices[@]}")
    ((${#selected[@]} > 0)) || exit 0
  fi

  [[ -n $mode ]] || mode=$(choose_mode)

  local rc=0
  apply_agent "$agent" "$mode" "${selected[@]}" || rc=$?
  [[ $mode == apply ]] && monitoring_server_hint
  return "$rc"
}

# --- device add -----------------------------------------------------------

# Values of `category`; must match deviceCategories in lib/inventory.nix.
CATEGORIES=(proxmox proxmox-guest pi network)

task_device_add() {
  (($# == 0)) || die "device add takes no options; it asks for everything"
  load_inventory

  local taken
  taken=$(jq -r '(.machines | keys[]), (.devices | keys[]),
    (.machines[] | .ssh.aliases // {} | keys[]), (.devices[] | .ssh // {} | keys[])' <<<"$inventory")

  local name description ip user port category baremetal ping agents=()
  while :; do
    name=$(gum input --header "Device name (also its SSH alias)" --placeholder "e.g. nas") || exit 0
    if [[ ! $name =~ ^[a-z][a-z0-9-]*$ ]]; then
      warn "Use lower-case letters, digits and -, starting with a letter."
    elif grep -qx -- "$name" <<<"$taken"; then
      warn "$name is already a machine, device or SSH alias."
    else
      break
    fi
  done
  description=$(gum input --header "Description" --placeholder "e.g. Debian VM with Nextcloud (Proxmox guest)") || exit 0
  while :; do
    ip=$(gum input --header "LAN address (static, outside the DHCP pool)" --placeholder "192.168.50.x") || exit 0
    [[ $ip =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] && break
    warn "Not an IPv4 address."
  done
  user=$(gum input --header "SSH user" --value root) || exit 0
  while :; do
    port=$(gum input --header "SSH port" --value 22) || exit 0
    [[ $port =~ ^[0-9]+$ ]] && break
    warn "Not a port number."
  done
  category=$(gum choose --header "Category (tiles of the fleet overview)" none "${CATEGORIES[@]}") || exit 0
  if gum confirm "Real hardware (baremetal: temperature and SMART alerts)?" --default=false; then
    baremetal=true
  else
    baremetal=false
  fi
  if gum confirm "Ping it (HostDown alert)? Say no for devices that are often off."; then
    ping=true
  else
    ping=false
  fi
  local choices=() a
  for a in "${AGENTS[@]}"; do
    [[ ${a%%|*} == smartctl && $baremetal == false ]] && continue
    choices+=("${a%%|*}")
  done
  mapfile -t agents < <(gum choose --no-limit \
    --header "Monitoring agents to install with Ansible (space toggles; none is fine)" "${choices[@]}")

  # Write the file. Fields as described in hosts/README.md.
  local file="hosts/devices/$name.nix" monitoring_lines=""
  [[ $ping == true ]] && monitoring_lines+="    ping = true;"$'\n'
  for a in "${agents[@]}"; do
    monitoring_lines+="    $a = true;"$'\n'
  done
  {
    printf '# hosts/devices/%s.nix - fields are described in hosts/README.md\n' "$name"
    # shellcheck disable=SC2016 # the backticks are part of the comment text
    printf '# Added with `nix run .#fleet` (device add) on %s.\n' "$(date +%F)"
    printf '{\n'
    printf '  description = %s;\n' "$(nix_string "$description")"
    printf '  lan.ip = %s;\n' "$(nix_string "$ip")"
    if [[ $port == 22 ]]; then
      printf '  ssh.%s.user = %s;\n' "$name" "$(nix_string "$user")"
    else
      printf '  ssh.%s = {\n    user = %s;\n    port = %s;\n  };\n' "$name" "$(nix_string "$user")" "$port"
    fi
    [[ $category != none ]] && printf '  category = %s;\n' "$(nix_string "$category")"
    [[ $baremetal == true ]] && printf '  baremetal = true;\n'
    if [[ -n $monitoring_lines ]]; then
      printf '  monitoring = {\n%s  };\n' "$monitoring_lines"
    fi
    printf '}\n'
  } >"$file"
  alejandra -q "$file" || true

  # The flake sees only files known to git.
  git add -- "$file"
  info "Validating the inventory with the new device..."
  if ! inventory=$(nix eval --json .#inventory); then
    git rm -q --cached -- "$file"
    rm -f -- "$file"
    die "the new device makes the inventory invalid (see above); nothing was kept"
  fi
  local server
  server=$(jq -r '.monitoring.server' <<<"$inventory")
  info "Checking that the monitoring server ($server) still evaluates..."
  if ! nix eval --json ".#nixosConfigurations.$server.config.services.prometheus.scrapeConfigs" >/dev/null; then
    git rm -q --cached -- "$file"
    rm -f -- "$file"
    die "the monitoring server does not evaluate with the new device; nothing was kept"
  fi

  info "Wrote and staged $file:"
  cat -- "$file"

  # Agents now, if this workstation already knows the SSH alias (it does
  # not until Home Manager has generated ~/.ssh/config.d/devices with the
  # new device, i.e. after a rebuild).
  local pending=()
  if ((${#agents[@]} > 0)); then
    if [[ -n $(missing_ssh_aliases "$name") ]]; then
      pending=("${agents[@]}")
    elif gum confirm "Install the agents (${agents[*]}) on $name now?"; then
      local mode
      mode=$(choose_mode)
      for a in "${agents[@]}"; do
        apply_agent "$a" "$mode" "$name" || warn "$a on $name: see above"
      done
    else
      pending=("${agents[@]}")
    fi
  fi

  # The commit message goes between double quotes on the shell: no ", $,
  # backtick or backslash from the description.
  local summary=${description//[\"\$\`\\]/} step=1
  printf '\nNext steps:\n\n'
  printf '  %d. git commit -m "devices: add %s (%s)" -- %s\n' "$step" "$name" "$summary" "$file"
  step=$((step + 1))
  if ((${#pending[@]} > 0)); then
    printf '  %d. rebuild this workstation (nrs), so ssh knows the alias %s\n' "$step" "$name"
    step=$((step + 1))
    for a in "${pending[@]}"; do
      printf '  %d. nix run .#fleet -- monitoring apply --agent %s --limit %s\n' "$step" "$a" "$name"
      step=$((step + 1))
    done
  fi
  if [[ $ping == true || ${#agents[@]} -gt 0 ]]; then
    printf '  %d. colmena apply --on %s   (Prometheus targets)\n' "$step" "$server"
  fi
  printf '\n'
  return 0
}

# --- dispatch -------------------------------------------------------------

root=$(git rev-parse --show-toplevel 2>/dev/null) || die "run it inside the nixos repository"
cd "$root"
[[ -f flake.nix && -d hosts/machines ]] || die "run it inside the nixos repository"

case ${1:-} in
  -h | --help)
    usage
    exit 0
    ;;
esac

if (($# == 0)); then
  read -r -a words <<<"$(pick_task)"
  ((${#words[@]} > 0)) || exit 0
  set -- "${words[@]}"
fi

task="${1:-} ${2:-}"
shift $(($# < 2 ? $# : 2))

case $task in
  "device add") task_device_add "$@" ;;
  "monitoring apply") task_monitoring_apply "$@" ;;
  "host new") exec nix run .#new-host -- "$@" ;;
  "host install") exec nix run .#install-host -- "$@" ;;
  "secrets update") exec nix run .#sops-config -- "$@" ;;
  *)
    usage >&2
    exit 1
    ;;
esac
